robo-client/RoboClient/Models/RoboContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace RoboClient.Models
{
    public class RoboContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public RoboContext() : base("name=RoboContext")
        {
        }

        public System.Data.Entity.DbSet<RoboClient.Models.Robos.Robo> Roboes { get; set; }
    }
}

robo-client/RoboClient/Models/Robos/Braco.cs
using System.ComponentModel.DataAnnotations;

namespace RoboClient.Models.Robos
{
    public class Braco
    {
        [Key] public string Id { get; set; }
        public Pulso Pulso { get; set; }
        public Cotovelo Cotovelo { get; set; }
    }
}

robo-client/RoboClient/Models/Robos/Cabeca.cs
using System.ComponentModel.DataAnnotations;

namespace RoboClient.Models.Robos
{
    public class Cabeca
    {
        [Key] public string Id { get; set; }
        public int Posicao { get; set; }
        public int Rotacao { get; set; }
    }
}

robo-client/RoboClient/Models/Robos/Cotovelo.cs
using System.ComponentModel.DataAnnotations;

namespace RoboClient.Models.Robos
{
    public class Cotovelo
    {
        [Key] public string Id { get; set; }
        public int Posicao { get; set; }
    }
}

robo-client/RoboClient/Models/Robos/Pulso.cs
using System.ComponentModel.DataAnnotations;

namespace RoboClient.Models.Robos
{
    public class Pulso
    {
        [Key] public string Id { get; set; }
        public int Posicao { get; set; }
    }
}

robo-client/RoboClient/Models/Robos/Robo.cs
using System.ComponentModel.DataAnnotations;

namespace RoboClient.Models.Robos
{
    public class Robo
    {
        [Key] public string Id { get; set; }
        public Cabeca Cabeca { get; set; }
        public Braco BracoDireito { get; set; }
        public Braco BracoEsquerdo { get; set; }

        public int CabecaPosicao => Cabeca?.Posicao ?? 0;
        public int CabecaRotacao => Cabeca?.Rotacao ?? 0;
        public int PulsoDireitoPosicao => BracoDireito?.Pulso?.Posicao ?? 0;
        public int CotoveloDireitoPosicao => BracoDireito?.Cotovelo?.Posicao ?? 0;
        public int PulsoEsquerdoPosicao => BracoEsquerdo?.Pulso?.Posicao ?? 0;
        public int CotoveloEsquerdoPosicao => BracoEsquerdo?.Cotovelo?.Posicao ?? 0;
    }
}

robo-client/RoboClient/Controllers/HomeController.cs
using System.Web.Mvc;

namespace RoboClient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

robo-client/RoboClient/Controllers/RobosController.cs
using RoboClient.Models.Robos;
using RoboClient.Services;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace RoboClient.Controllers
{
    public class RobosController : Controller
    {
        private readonly RoboApiService _api = new RoboApiService();
        private static IList<Robo> _robos;

        public RobosController()
        {
            if (_robos == null)
                _robos = new List<Robo>();
        }

        public ActionResult Index()
        {
            return View(_robos);
        }

        public async Task<ActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var robo = await _api.GetAsync<Robo>(id);
            if (robo == null)
                return HttpNotFound();

            return View(robo);
        }

        public async Task<ActionResult> Create()
        {
            var robo = await _api.GetAsync<Robo>();
            _robos.Add(robo);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var robo = await _api.GetAsync<Robo>(id);
            if (robo == null)
                return HttpNotFound();

            return View(robo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Cabeca,BracoDireito,BracoEsquerdo")] Robo robo)
        {
            if (ModelState.IsValid)
            {
                await _api.PutAsync<Robo>(robo);
                return RedirectToAction("Index");
            }
            return View(robo);
        }
    }
}

robo-client/RoboClient/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

robo-client/RoboClient/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

robo-client/RoboClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

robo-client/RoboClient/Views/Robos/Create.cshtml
@model RoboClient.Models.Robos.Robo

@{
    ViewBag.Title = "Novo";
}

<h2>Novo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Robo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

robo-client/RoboClient/Views/Robos/Delete.cshtml
@model RoboClient.Models.Robos.Robo

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Robo</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para a lista", "Index")
        </div>
    }
</div>

robo-client/RoboClient/Views/Robos/Details.cshtml
@model RoboClient.Models.Robos.Robo

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Robo</h4>
    <hr />
    <dl class="dl-horizontal"></dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar para a lista", "Index")
</p>

<p>@Model.Id</p>

<ul>
    <li>
        Cabeça
        <ul>
            <li>Rotação: @Model.Cabeca.Rotacao</li>
            <li>Inclinação: @Model.Cabeca.Rotacao</li>
        </ul>
    </li>
    <li>
        Braço direito
        <ul>
            <li>Rotação pulso: @Model.PulsoDireitoPosicao</li>
            <li>Posição cotovelo: @Model.CotoveloDireitoPosicao</li>
        </ul>
    </li>
    <li>
        Braço esquerdo
        <ul>
            <li>Rotação pulso: @Model.PulsoEsquerdoPosicao</li>
            <li>Posição cotovelo: @Model.CotoveloEsquerdoPosicao</li>
        </ul>
    </li>
</ul>

robo-client/RoboClient/Views/Robos/Edit.cshtml
@model RoboClient.Models.Robos.Robo

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Robo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        
        <div class="form-group">
            <p class="control-label col-md-2">Inclinação da cabeça</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cabeca.Posicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cabeca.Posicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Rotação da cabeça</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cabeca.Rotacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cabeca.Rotacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Posição do pulso direito</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BracoDireito.Pulso.Posicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BracoDireito.Pulso.Posicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Posição do cotovelo direito</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BracoDireito.Cotovelo.Posicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BracoDireito.Cotovelo.Posicao, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <p class="control-label col-md-2">Posição do pulso esquerdo</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BracoEsquerdo.Pulso.Posicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BracoEsquerdo.Pulso.Posicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Posição do cotovelo esquerdo</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BracoEsquerdo.Cotovelo.Posicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BracoEsquerdo.Cotovelo.Posicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

robo-client/RoboClient/Views/Robos/Index.cshtml
@model IEnumerable<RoboClient.Models.Robos.Robo>

@{
    ViewBag.Title = "Lista";
}

<h2>Lista</h2>

<p>
    @Html.ActionLink("Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>ID</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @item.Id |
            @Html.ActionLink("Editar", "Edit", new {id = item.Id}) |
            @Html.ActionLink("Visualizar", "Details", new {id = item.Id}) |            
        </td>
    </tr>
}

</table>

robo-client/RoboClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - R.O.B.O</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("R.O.B.O (Robô Operacional Binariamente Orientado)", "Index", "Robos", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Alan Minusculi</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>